[general]
connection = "Data Source=.\\temp.sqlite3"
output = "Schema.fs"
namespace = "Schema"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
